# Generated by Django 5.1.2 on 2026-02-10 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_applications', models.IntegerField(default=0)),
                ('new_applicants', models.IntegerField(default=0)),
                ('reviews_completed', models.IntegerField(default=0)),
                ('documents_verified', models.IntegerField(default=0)),
                ('avg_review_time_minutes', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
            options={
                'db_table': 'analytics_daily',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='analytics_d_date_9d1a51_idx')],
            },
        ),
    ]
