# Generated by Django 5.1.2 on 2026-02-10 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('iso_code', models.CharField(max_length=3, unique=True)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('timezone', models.CharField(blank=True, max_length=100)),
                ('currency', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'db_table': 'countries',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='countries_name_19480f_idx'), models.Index(fields=['iso_code'], name='countries_iso_cod_069113_idx')],
            },
        ),
    ]
