# Generated by Django 5.1.2 on 2026-02-10 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('qs_university_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('website_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universities', to='countries.country')),
            ],
            options={
                'db_table': 'universities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('BACHELOR', 'Bachelor'), ('MASTER', 'Master'), ('PHD', 'PhD')], max_length=20)),
                ('intake_period', models.CharField(max_length=100)),
                ('duration_months', models.IntegerField()),
                ('tuition_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='universities.university')),
            ],
            options={
                'db_table': 'programs',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='university',
            index=models.Index(fields=['name'], name='universitie_name_3cb454_idx'),
        ),
        migrations.AddIndex(
            model_name='university',
            index=models.Index(fields=['country'], name='universitie_country_6bc3e7_idx'),
        ),
        migrations.AddIndex(
            model_name='university',
            index=models.Index(fields=['qs_university_id'], name='universitie_qs_univ_007942_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['university'], name='programs_univers_96f42c_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['name'], name='programs_name_c4324d_idx'),
        ),
    ]
