# Generated by Django 4.2.28 on 2026-02-07 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("APPLICATION_SUBMITTED", "Application Submitted"),
                            ("APPLICATION_UPDATED", "Application Updated"),
                            ("DOCUMENT_VERIFIED", "Document Verified"),
                            ("DOCUMENT_REJECTED", "Document Rejected"),
                            ("REVIEW_ASSIGNED", "Review Assigned"),
                            ("REVIEW_COMPLETED", "Review Completed"),
                            ("STATUS_CHANGED", "Status Changed"),
                            ("RECOMMENDATION_REQUEST", "Recommendation Request"),
                            ("PASSED", "Application Passed"),
                            ("REJECTED", "Application Rejected"),
                            ("NEEDS_REVISION", "Revision Needed"),
                            ("GENERAL", "General Notification"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                (
                    "body_html",
                    models.TextField(
                        help_text="HTML email body with template variables"
                    ),
                ),
                ("body_text", models.TextField(help_text="Plain text version")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "email_templates",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("APPLICATION_SUBMITTED", "Application Submitted"),
                            ("APPLICATION_UPDATED", "Application Updated"),
                            ("DOCUMENT_VERIFIED", "Document Verified"),
                            ("DOCUMENT_REJECTED", "Document Rejected"),
                            ("REVIEW_ASSIGNED", "Review Assigned"),
                            ("REVIEW_COMPLETED", "Review Completed"),
                            ("STATUS_CHANGED", "Status Changed"),
                            ("RECOMMENDATION_REQUEST", "Recommendation Request"),
                            ("PASSED", "Application Passed"),
                            ("REJECTED", "Application Rejected"),
                            ("NEEDS_REVISION", "Revision Needed"),
                            ("GENERAL", "General Notification"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("action_url", models.CharField(blank=True, max_length=500)),
                ("action_label", models.CharField(blank=True, max_length=100)),
                ("application_id", models.IntegerField(blank=True, null=True)),
                ("document_id", models.IntegerField(blank=True, null=True)),
                ("review_id", models.IntegerField(blank=True, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("is_sent_email", models.BooleanField(default=False)),
                ("email_sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read"],
                        name="notificatio_user_id_a4dd5c_idx",
                    ),
                    models.Index(
                        fields=["notification_type"],
                        name="notificatio_notific_19df93_idx",
                    ),
                ],
            },
        ),
    ]
