# Generated by Django 5.1.2 on 2026-02-10 22:37

import django.db.models.deletion
from django.db import migrations, models


def seed_roles_and_map_users(apps, schema_editor):
    Role = apps.get_model('accounts', 'Role')
    User = apps.get_model('accounts', 'User')

    role_definitions = {
        'STUDENT': 'Applicant',
        'CHECKER': 'Reviewer',
        'ADMIN': 'Administrator',
    }

    role_map = {}
    for code, name in role_definitions.items():
        role_obj = Role.objects.create(code=code, name=name)
        role_map[code] = role_obj.id

    for user in User.objects.all():
        role_code = user.role
        if role_code in role_map:
            user.role = str(role_map[role_code])
            user.save(update_fields=['role'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'permissions',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('STUDENT', 'Student'), ('CHECKER', 'Admission Checker'), ('ADMIN', 'Administrator')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'roles',
                'ordering': ['code'],
            },
        ),
        migrations.RunPython(seed_roles_and_map_users, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, db_column='role_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='accounts.role'),
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='accounts.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='accounts.role')),
            ],
            options={
                'db_table': 'role_permissions',
                'unique_together': {('role', 'permission')},
            },
        ),
    ]
