# Generated by Django 4.2.28 on 2026-02-07 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "program_name",
                    models.CharField(help_text="Program applying for", max_length=255),
                ),
                (
                    "academic_year",
                    models.CharField(help_text="e.g., 2026-2027", max_length=20),
                ),
                (
                    "intake_period",
                    models.CharField(help_text="e.g., Fall 2026", max_length=50),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("DOCUMENTS_INCOMPLETE", "Documents Incomplete"),
                            ("PASSED", "Passed"),
                            ("REJECTED", "Rejected"),
                            ("NEEDS_REVISION", "Needs Revision"),
                            ("FORWARDED_TO_QS", "Forwarded to QS"),
                        ],
                        default="DRAFT",
                        max_length=30,
                    ),
                ),
                (
                    "current_stage",
                    models.CharField(
                        choices=[
                            ("INITIAL_SUBMISSION", "Initial Submission"),
                            ("DOCUMENT_VERIFICATION", "Document Verification"),
                            ("ESSAY_REVIEW", "Essay Review"),
                            ("FINAL_REVIEW", "Final Review"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="INITIAL_SUBMISSION",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("review_started_at", models.DateTimeField(blank=True, null=True)),
                ("review_completed_at", models.DateTimeField(blank=True, null=True)),
                ("personal_statement", models.TextField(blank=True)),
                ("additional_info", models.TextField(blank=True)),
                ("is_complete", models.BooleanField(default=False)),
                ("requires_attention", models.BooleanField(default=False)),
                (
                    "assigned_checker",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "CHECKER"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "STUDENT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "applications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationTimeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("previous_status", models.CharField(blank=True, max_length=30)),
                ("new_status", models.CharField(blank=True, max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline",
                        to="applications.application",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "application_timeline",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["student", "status"], name="application_student_a8a36b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["assigned_checker", "status"],
                name="application_assigne_e0431a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["status", "current_stage"], name="application_status_f8f5ce_idx"
            ),
        ),
    ]
