# Generated by Django 5.1.2 on 2026-02-10 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QSRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qs_university_id', models.CharField(max_length=50)),
                ('university_name', models.CharField(max_length=255)),
                ('rank_global', models.IntegerField()),
                ('rank_year', models.IntegerField()),
                ('score_overall', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('snapshot_date', models.DateField()),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='countries.country')),
            ],
            options={
                'db_table': 'qs_rankings',
                'ordering': ['rank_global'],
                'indexes': [models.Index(fields=['qs_university_id'], name='qs_rankings_qs_univ_f35d4e_idx'), models.Index(fields=['rank_year'], name='qs_rankings_rank_ye_005344_idx'), models.Index(fields=['country'], name='qs_rankings_country_dd8b10_idx')],
                'constraints': [models.UniqueConstraint(fields=('qs_university_id', 'rank_year', 'snapshot_date'), name='unique_qs_snapshot')],
            },
        ),
    ]
