# Generated by Django 4.2.28 on 2026-02-07 12:03

import apps.documents.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("TRANSCRIPT", "Academic Transcript"),
                            ("TEST_SCORE", "Standardized Test Score"),
                            ("ESSAY", "Essay/Personal Statement"),
                            ("RECOMMENDATION_LETTER", "Recommendation Letter"),
                            ("PORTFOLIO", "Portfolio"),
                            ("CERTIFICATE", "Certificate"),
                            ("ID_DOCUMENT", "ID Document"),
                            ("OTHER", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.documents.models.document_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                ]
                            )
                        ],
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file_size", models.IntegerField(help_text="File size in bytes")),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                (
                    "title",
                    models.CharField(
                        help_text="Document title/description", max_length=255
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Verification"),
                            ("VERIFIED", "Verified"),
                            ("REJECTED", "Rejected"),
                            ("NEEDS_RESUBMISSION", "Needs Resubmission"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("verification_notes", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_confidential", models.BooleanField(default=False)),
                ("recommender_name", models.CharField(blank=True, max_length=255)),
                ("recommender_email", models.EmailField(blank=True, max_length=254)),
                ("recommender_title", models.CharField(blank=True, max_length=255)),
                (
                    "recommender_institution",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="applications.application",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "documents",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="RecommendationLetterRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recommender_name", models.CharField(max_length=255)),
                ("recommender_email", models.EmailField(max_length=254)),
                ("recommender_title", models.CharField(max_length=255)),
                ("recommender_institution", models.CharField(max_length=255)),
                (
                    "relationship",
                    models.CharField(
                        help_text="Relationship to student", max_length=255
                    ),
                ),
                (
                    "request_token",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_submitted", models.BooleanField(default=False)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("reminder_count", models.IntegerField(default=0)),
                ("last_reminder_sent", models.DateTimeField(blank=True, null=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_requests",
                        to="applications.application",
                    ),
                ),
                (
                    "document",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendation_request",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "db_table": "recommendation_letter_requests",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["application", "document_type"],
                name="documents_applica_c4dec9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["status"], name="documents_status_f31a08_idx"),
        ),
    ]
