# Generated by Django 4.2.28 on 2026-02-07 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("applications", "0001_initial"),
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "overall_score",
                    models.IntegerField(
                        blank=True, help_text="Overall score (1-10)", null=True
                    ),
                ),
                (
                    "academic_score",
                    models.IntegerField(
                        blank=True, help_text="Academic performance (1-10)", null=True
                    ),
                ),
                (
                    "essay_score",
                    models.IntegerField(
                        blank=True, help_text="Essay quality (1-10)", null=True
                    ),
                ),
                (
                    "recommendation_score",
                    models.IntegerField(
                        blank=True, help_text="Recommendations (1-10)", null=True
                    ),
                ),
                (
                    "extracurricular_score",
                    models.IntegerField(
                        blank=True, help_text="Extracurriculars (1-10)", null=True
                    ),
                ),
                (
                    "internal_notes",
                    models.TextField(
                        blank=True, help_text="Internal notes (not visible to student)"
                    ),
                ),
                (
                    "feedback_to_student",
                    models.TextField(
                        blank=True, help_text="Feedback visible to student"
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PASS", "Pass to Next Stage"),
                            ("REJECT", "Reject"),
                            ("REQUEST_CLARIFICATION", "Request Clarification"),
                            ("FORWARD_TO_QS", "Forward to QS"),
                        ],
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                ("is_complete", models.BooleanField(default=False)),
                ("requires_attention", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="applications.application",
                    ),
                ),
                (
                    "checker",
                    models.ForeignKey(
                        limit_choices_to={"role": "CHECKER"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conducted_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_authentic", models.BooleanField(blank=True, null=True)),
                ("is_complete", models.BooleanField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="documents.document",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_reviews",
                        to="reviews.review",
                    ),
                ),
            ],
            options={
                "db_table": "document_reviews",
            },
        ),
        migrations.CreateModel(
            name="ReviewTagAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        choices=[
                            ("STRONG", "Strong Candidate"),
                            ("MEDIUM", "Medium Candidate"),
                            ("WEAK", "Weak Candidate"),
                            ("MISSING_DOCUMENTS", "Missing Documents"),
                            ("SUSPECTED_FRAUD", "Suspected Fraud"),
                            ("EXCELLENT_ESSAY", "Excellent Essay"),
                            ("WEAK_ESSAY", "Weak Essay"),
                            ("STRONG_RECOMMENDATIONS", "Strong Recommendations"),
                            ("NEEDS_INTERVIEW", "Needs Interview"),
                        ],
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="reviews.review",
                    ),
                ),
            ],
            options={
                "db_table": "review_tags",
                "unique_together": {("review", "tag")},
            },
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["application", "checker"], name="reviews_applica_c06f2d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["decision"], name="reviews_decisio_2d7d97_idx"),
        ),
    ]
